Added ssh to allowed values
netascode/terraform-aci-filter pull request #5
Opened 2022-05-17 15:56 UTC by techBeck03

Added `ssh` to allowed values and alphabetized allowed values following `unspecified`

2022-05-17 20:06 UTC, danischm requested changes
Thx, Brandon! You would need to install and run the pre-commit hooks once to update the documentation (readme) accordingly.

2022-05-19 14:13 UTC, techBeck03 commented
Done

2022-05-19 14:27 UTC, danischm approved these changes

2022-05-19 14:28 UTC, merged

2022-05-19 14:28 UTC, danischm commented
Thx, Brandon!